dist: bionic
  
language: python
python:
    - 3.8
    - 3.7
    - 3.6

before_install:
    - pip install invoke
    - pip install -r requirements.txt
    
install: skip

script: 
    - cp tests/files/token_storage.json search/
    - cat search/token_storage.json
    - python test_digikey_api.py
    - cat search/token_storage.json
