dist: bionic

branches:
  only:
  - master
  
language: python
python:
    - 3.8
    - 3.7
    - 3.6
matrix:
    allow_failures:
        - python: 3.7
        - python: 3.6

# Reference: https://docs.coveralls.io/parallel-build-webhook
# env:
#   global:
#     - COVERALLS_PARALLEL=true
notifications:
    webhooks: https://coveralls.io/webhook

apt-packages:
    - sqlite3

before_install:
    - pip install invoke
    # Check syntax
    - invoke style
    # InvenTree Setup
    - git clone https://github.com/inventree/InvenTree/
    - cp tests/files/inventree_default_db.sqlite3 InvenTree/
    - cd InvenTree/ && invoke install && invoke migrate && cd -
    # Ki-nTree setup
    # Remove inventree as conflict with submodule
    - pip uninstall inventree -y
    - invoke install
    - cp tests/files/results.tgz search/
    - cp tests/files/inventree_test.yaml config/inventree/
    - cd search/ && tar xvf results.tgz && cd -
    # Digi-Key token
    - git config --global user.email "travis@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git clone https://${GH_TOKEN}@github.com/eeintech/digikey-token.git
    - cp digikey-token/token_storage.json search/
    - cat search/token_storage.json
    
install: skip

script: invoke test

after_success:
    # Digi-Key token
    - cat search/token_storage.json
    - cp search/token_storage.json digikey-token/
    - cd digikey-token
    - git add -u
    - git commit -m "Updated token"
    - git push origin master
    - cd ..
    # Coveralls
    - coveralls
    # Build
    - invoke build